### ISSUE TITLE
feature request: configuration file!

### ISSUE THREAD

**Issue by D33M0N** [aokellermann/yaycache#2]
look the `paccache-hook` AUR package for inspiration :-)

**Comment by aokellermann** [comment]
AUR package `yaycache-hook` is now available

**Comment by aokellermann** [comment]
@KAGEYAM4 yes

**Comment by D33M0N** [comment]
With yaycache I used `yaycache -ruk0 --min-mtime "30 days ago" -v`

Now trying to convert it into the hook I put initially:
`uninstalled_extra_args=' --min-mtime "30 days ago"'`

but I got this:
```
Removing old uninstalled AUR packages...
date: invalid date ‘"30’
==> ERROR: argument to option --min-mtime must be of the form described by 'info "Date input formats" '.
error: command failed to execute correctly
```

then I changed it to:
`uninstalled_extra_args="--min-mtime '30 days ago'"`

and then i got:
```
Removing old uninstalled AUR packages...
date: invalid date ‘'30’
==> ERROR: argument to option --min-mtime must be of the form described by 'info "Date input formats" '.
error: command failed to execute correctly
```

What am I doing wrong here?

**Comment by KAGEYAM4** [comment]
@D33M0N  it could be the level of quoting, use this in yaycache-hook.conf - `uninstalled_extra_args="'--min-mtime=30 days ago'"`, as you can see the whole arg is quoted with `' '` and then again with `" "`, so it stops word splitting two times.

Whereas ` uninstalled_extra_args="--min-mtime '30 days ago'"`, here one whole quoting is done using `' '` then the args will split into `--min-mtime` and `'30 days ago'`.
