### ISSUE TITLE
`/etc/yaycache-hook.conf` is this .conf only used by hook and not by .timer/.service file?

### ISSUE THREAD

**Issue by KAGEYAM4** [aokellermann/yaycache#5]
I am confused by wether `/etc/yaycache-hook.conf` is used by in all three cases ->
1. yaycachehook
2. yaycache.service
3. yaycache.timer 

and do you have any idea about `/etc/paccache-hook.conf` ?

**Comment by aokellermann** [comment]
yaycache.timer and yaycache.service are unrelated to yaycache-hook. I imagine the same is true for paccache
